name: Question
description: Ask a question about the repository
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What's your question about?
      options:
        - Setup/installation
        - How to use the repository
        - Specific problem/solution
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "Example: How do I run tests for a specific problem?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help us answer?
      placeholder: "Example: I'm working on problem 15, and I see test_palindrome.py but don't know how to run it."
    validations:
      required: false
